ALTER TABLE USERS ALTER COLUMN user_id RESTART WITH 1;
ALTER TABLE FILMS ALTER COLUMN film_id RESTART WITH 1;
ALTER TABLE MPA ALTER COLUMN MPA_ID RESTART WITH 1;
ALTER TABLE GENRE ALTER COLUMN GENRE_ID RESTART WITH 1;

-- INSERT INTO GENRE(GENRE_NAME) VALUES ('Комедия');
-- INSERT INTO GENRE(GENRE_NAME) VALUES ('Драма');
-- INSERT INTO GENRE(GENRE_NAME) VALUES ('Мультфильм');
-- INSERT INTO GENRE(GENRE_NAME) VALUES ('Триллер');
-- INSERT INTO GENRE(GENRE_NAME) VALUES ('Документальный');
-- INSERT INTO GENRE(GENRE_NAME) VALUES ('Боевик');
--
-- INSERT INTO MPA(MPA_NAME) VALUES('G');
-- INSERT INTO MPA(MPA_NAME) VALUES('PG');
-- INSERT INTO MPA(MPA_NAME) VALUES('PG-13');
-- INSERT INTO MPA(MPA_NAME) VALUES('R');
-- INSERT INTO MPA(MPA_NAME) VALUES('NC-17');
