

CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID   INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL     VARCHAR(100) NOT NULL,
    LOGIN     VARCHAR(100) NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    BIRTHDAY  DATE
    );
CREATE TABLE IF NOT EXISTS FILMS
(
    FILM_ID INT PRIMARY KEY AUTO_INCREMENT,
    FILM_NAME VARCHAR(100) NOT NULL,
    FILM_DESCRIPTION VARCHAR(200) NOT NULL,
    RELEASE_DATE DATE,
    DURATION INTEGER,
    LIKES INTEGER
);
CREATE TABLE IF NOT EXISTS GENRE
(
    GENRE_ID INT PRIMARY KEY AUTO_INCREMENT,
    GENRE_NAME VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS MPA
(
    MPA_ID INT PRIMARY KEY AUTO_INCREMENT,
    MPA_NAME VARCHAR(50)
);
